--- 
abstract: Moosic client library for Perl
author: 
  - Florian Ragwitz <rafl@debian.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Audio-Moosic
no_index: 
  directory: 
    - inc
    - t
requires: 
  RPC::XML: 0
version: 0.10
